name: Deploy React Application
on:
  push:
    branches:
      - skillup-ec2-docker-ssl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t savinduc/skillup-frontend --build-arg VITE_API_URL='${{ secrets.VITE_API_URL }}' .
      - name: Publish Image to docker hub
        run: docker push savinduc/skillup-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull savinduc/skillup-frontend:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container savinduc/skillup-frontend